'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace MailServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute([Namespace]:="http://localhost/", ConfigurationName:="MailServiceReference.MailServiceSoap")>  _
    Public Interface MailServiceSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/HelloWorld", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function HelloWorld() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/SendMail", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub SendMail()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/SendMail", ReplyAction:="*")>  _
        Function SendMailAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/sendsms", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub sendsms()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/sendsms", ReplyAction:="*")>  _
        Function sendsmsAsync() As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/sendbudgetsms", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Sub sendbudgetsms()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://localhost/sendbudgetsms", ReplyAction:="*")>  _
        Function sendbudgetsmsAsync() As System.Threading.Tasks.Task
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface MailServiceSoapChannel
        Inherits MailServiceReference.MailServiceSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class MailServiceSoapClient
        Inherits System.ServiceModel.ClientBase(Of MailServiceReference.MailServiceSoap)
        Implements MailServiceReference.MailServiceSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function HelloWorld() As String Implements MailServiceReference.MailServiceSoap.HelloWorld
            Return MyBase.Channel.HelloWorld
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of String) Implements MailServiceReference.MailServiceSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync
        End Function
        
        Public Sub SendMail() Implements MailServiceReference.MailServiceSoap.SendMail
            MyBase.Channel.SendMail
        End Sub
        
        Public Function SendMailAsync() As System.Threading.Tasks.Task Implements MailServiceReference.MailServiceSoap.SendMailAsync
            Return MyBase.Channel.SendMailAsync
        End Function
        
        Public Sub sendsms() Implements MailServiceReference.MailServiceSoap.sendsms
            MyBase.Channel.sendsms
        End Sub
        
        Public Function sendsmsAsync() As System.Threading.Tasks.Task Implements MailServiceReference.MailServiceSoap.sendsmsAsync
            Return MyBase.Channel.sendsmsAsync
        End Function
        
        Public Sub sendbudgetsms() Implements MailServiceReference.MailServiceSoap.sendbudgetsms
            MyBase.Channel.sendbudgetsms
        End Sub
        
        Public Function sendbudgetsmsAsync() As System.Threading.Tasks.Task Implements MailServiceReference.MailServiceSoap.sendbudgetsmsAsync
            Return MyBase.Channel.sendbudgetsmsAsync
        End Function
    End Class
End Namespace
